# Generated by Django 4.1.12 on 2023-11-06 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula', models.BigIntegerField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('nombre_contacto_emergencia', models.CharField(max_length=255)),
                ('relacion_paciente', models.CharField(max_length=50)),
                ('nro_contact_emer', models.CharField(max_length=15)),
                ('nombre_seguro', models.CharField(max_length=100)),
                ('nropoliza', models.CharField(max_length=20)),
                ('estadopoliza', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.BigIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('asistencia', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.usuario')),
            ],
        ),
    ]
