# Generated by Django 4.1.12 on 2023-11-07 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(max_length=50)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulso', models.PositiveSmallIntegerField()),
                ('nivel_oxigeno', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medicamentos_administrados', models.TextField()),
                ('pruebas_realizadas', models.TextField()),
                ('observaciones', models.TextField()),
                ('recordatorio_visita', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
            ],
        ),
    ]
