# Generated by Django 4.1.12 on 2023-11-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0002_visitapaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.IntegerField()),
                ('cedula_paciente', models.CharField(max_length=20)),
                ('cedula_medico', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField()),
                ('tipo_orden', models.CharField(max_length=20)),
            ],
        ),
    ]
